server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: "localhost"
  port: 5432
  name: "eventos_db"
  user: "eventos_user"
  password: "eventos_password"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300s

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

rabbitmq:
  host: "localhost"
  port: 5672
  user: "eventos_user"
  password: "eventos_password"
  vhost: "/"

jwt:
  secret: "your-super-secret-jwt-key-change-in-production"
  expiration: 24h
  refresh_expiration: 168h

logging:
  level: "info"
  format: "json"
  output: "stdout"

monitoring:
  prometheus:
    enabled: true
    port: 9090
  
  tracing:
    enabled: true
    jaeger_endpoint: "http://localhost:14268/api/traces"

security:
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    expose_headers: ["*"]
    allow_credentials: true
    max_age: 86400

  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst: 10

pagination:
  default_page_size: 20
  max_page_size: 100
